# $schema: https://json.schemastore.org/ruff.json

line-length = 120
include = [
    "ruff.toml",
    "pyproject.toml",
    "src/**/*.py",
    "tests/**/*.py",
]

[lint]
preview = true
ignore = [
    "undocumented-public-module",    # 有时候文档不是必须的
    "undocumented-public-class",
    "undocumented-public-method",
    "undocumented-public-function",
    "undocumented-public-package",
    "undocumented-public-init",
    "import-outside-top-level", # 为了防止兼容性问题或者不必要的代码运行，需要将导入放到函数内。
    "magic-value-comparison", # 一些长度判断、常见状态码不需要常量
    "missing-type-kwargs",  # 无法做到
    "missing-return-type-undocumented-public-function",  # 为了保持简洁，None 类型不写返回类型
    "missing-return-type-private-function",
    "missing-return-type-special-method",
    "missing-trailing-comma",  # 可能与 Formatter 冲突
    "raise-vanilla-args",  # 没有必要嵌套业务错误类
    "raw-string-in-exception",
    "f-string-in-exception",
    "missing-copyright-notice", # 有例外版权再加
    "docstring-missing-returns", #有时这些文档说明不是必须的
    "docstring-missing-yields",
    "docstring-missing-exception",
    "non-empty-init-module",  # 该库的实现都放在 __init__.py 中
    "any-type",  # Any 有时因缺少泛型而不可避免
    "future-rewritable-type-annotation",  # 风险未知
]
select = [
    "correctness",
    "suspicious",
    "complexity",
    "performance",
    "style",
    "security",
    "formatting",
    "pedantic",
    "restriction",
]
allowed-confusables = ["，", "：", "（", "）", "；"] # 允许中文符号
exclude = ["tests/**"]

[lint.pydocstyle]
convention = "pep257"

[format]
docstring-code-format = true
line-ending = "lf"
