name: Testing

on:
  push:
    branches:
      - "releases/**"
    paths:
      - "**.py"
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: windows-latest # TODO: Use ubuntu-latest
    env:
      UV_NO_DEFAULT_GROUPS: true
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with pytest
        run: uv run --group test pytest
